spring:
  datasource:
    url: jdbc:mysql://localhost:3300/marketplacedb
    username: root
    password: 1324
  jpa:
    hibernate:
      # Recreate database on every run.
      # Options: none, validate, update, create, create-drop
      ddl-auto: create-drop
    # Enable SQL logging
    show-sql: true
    properties:
      hibernate:
        # Format SQL logs for easier reading.
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect