spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      # Recreate database on every run.
      ddl-auto: create-drop
    # Enable SQL logging
    show-sql: true
    properties:
      hibernate:
        # Format SQL logs for easier reading.
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect