variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check
build:
  stage: build
  script:
    - ./gradlew assemble
test:
  stage: test
  script:
    - ./gradlew test