name: CI

on:
  push:
    branches:
      - master  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the test job runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test
