name: Continuous Devlivery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build and push image to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: bryrmiginte
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: bryrmiginte/marketplace-backend:latest